### ISSUE TITLE
Ошибка в вызове

### ISSUE THREAD

**Issue by mkoreshkov** [modulbank-pay/modulbank-woocommerce#1]
Здравствуйте.

Временами появляется эта ошибка, в чём может быть дело? Она уведомляющая, но всё равно интересно.
WP 5.4.2, WC 4.2.2, плагин 1.9

`[Aug 24, 17:29:08] PHP Notice:  Функция total вызвана <strong>неправильно</strong>. Order properties should not be accessed directly. Backtrace: edit_post, wp_update_post, wp_insert_post, do_action('save_post'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Admin_Meta_Boxes->save_meta_boxes, do_action('woocommerce_process_shop_order_meta'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Meta_Box_Order_Data::save, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_changed'), WP_Hook->do_action, WP_Hook->apply_filters, carrotquest_hooks::order_status_changed, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong Дополнительную информацию можно найти на странице <a href="https://ru.wordpress.org/support/article/debugging-in-wordpress/">&laquo;Отладка в WordPress&raquo;</a>. (Это сообщение было добавлено в версии 3.0.) in /home/%directory%/wp-includes/functions.php on line 5167`

**Comment by VampiRUS** [comment]
Судя по логу, это в carrotquest плагине происходит.
